version: '3'

services:

  latest:
    image: 'tmvdl/yt-dl:latest'
    build: './src/latest'
    volumes: 
      - './src/latest:/app'

  dlp:
    image: 'tmvdl/yt-dl:dlp'
    build: './src/dlp'
    volumes: 
      - './src/dlp:/app'
