name: Docker pull

on:
  workflow_dispatch:
  schedule:
    - cron: '22 * * * *'

jobs:
  Docker-Pull:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker pull
        run: docker pull tmvdl/yt-dl -a
