name: Docker push

on:
  workflow_dispatch:
  schedule:
    - cron: '22 12 * * *'
  push:
    branches: 
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login in Docker Hub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}
      -
        name: Build Docker images
        run: sh env/build.sh
      -
        name: Push to Docker Hub
        run: docker push tmvdl/yt-dl -a
