name: Docker pull

on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:

jobs:
  Docker-Pull:
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull
        run: docker pull tmvdl/yt-dl -a
